# Generated by Django 2.0 on 2018-01-15 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=30)),
                ('index', models.CharField(blank=True, default='_', max_length=4)),
                ('wiki_index', models.CharField(blank=True, default='_', max_length=4)),
                ('year', models.IntegerField()),
                ('signature', models.CharField(max_length=15)),
                ('image', models.ImageField(max_length=130, upload_to='')),
            ],
            options={
                'ordering': ['-year', '-wiki_index'],
            },
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, max_length=130, null=True, upload_to='')),
                ('to_own', models.BooleanField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kapsle.Coin')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['coin'],
            },
        ),
        migrations.AddField(
            model_name='brewery',
            name='coin',
            field=models.ManyToManyField(to='kapsle.Coin'),
        ),
    ]
