# Generated by Django 2.0 on 2018-01-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0002_auto_20180115_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['brewery_name', 'index', 'year', 'wiki_index']},
        ),
    ]
