# Generated by Django 2.0 on 2018-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0003_auto_20180115_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='index',
            field=models.CharField(default='_', max_length=4),
        ),
        migrations.AlterField(
            model_name='coin',
            name='wiki_index',
            field=models.CharField(default='_', max_length=4),
        ),
    ]
