# Generated by Django 2.0 on 2018-01-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0005_auto_20180115_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoin',
            options={'ordering': ['-coin__year', '-coin__wiki_index', '-coin__index']},
        ),
    ]
