# Generated by Django 2.0 on 2018-01-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0009_coin_ignored_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ignorecoinlist',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='ignorecoinlist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='IgnoreCoinList',
        ),
    ]
