# Generated by Django 2.0 on 2018-01-29 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0012_auto_20180129_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ignored_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
