# Generated by Django 2.0 on 2018-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0014_brewery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='slug',
            field=models.SlugField(),
        ),
    ]
