# Generated by Django 2.0 on 2018-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0015_auto_20180129_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
