# Generated by Django 2.0 on 2018-01-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0016_auto_20180129_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='same_coin_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
