# Generated by Django 2.0 on 2018-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0018_remove_usercoin_same_coin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='kind',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('DUPLICATE', 'dubel')], default='DEFAULT', max_length=7),
        ),
    ]
