# Generated by Django 2.0 on 2018-02-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0019_usercoin_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoinCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoinKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kapsle.UserCoinKind'),
        ),
        migrations.AddField(
            model_name='usercoin',
            name='condition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kapsle.UserCoinCondition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercoin',
            name='types',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kapsle.UserCoinType'),
            preserve_default=False,
        ),
    ]
