# Generated by Django 2.0 on 2018-02-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0022_auto_20180207_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='ignored_by',
        ),
    ]
