# Generated by Django 2.0.2 on 2018-02-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0023_remove_coin_ignored_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['brewery', 'index', 'year', 'wiki_index']},
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='coin',
        ),
        migrations.AddField(
            model_name='coin',
            name='brewery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kapsle.Brewery'),
            preserve_default=False,
        ),
    ]
