# Generated by Django 2.0.2 on 2018-02-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsle', '0024_auto_20180211_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='brewery_name',
        ),
    ]
